# Generated by Django 5.2.2 on 2025-06-09 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('prestations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='prestataire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestataire', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commande',
            name='prestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestations.prestation'),
        ),
    ]
