# Generated by Django 5.2.2 on 2025-06-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('accepte', 'Acceptée'), ('termine', 'Terminé')], default='en attente', max_length=20),
        ),
    ]
