# Generated by Django 5.2.2 on 2025-08-28 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_alter_commande_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='prestataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestataire', to=settings.AUTH_USER_MODEL),
        ),
    ]
