# Generated by Django 5.2.2 on 2025-09-29 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_alter_commande_prestataire'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='service.service'),
        ),
    ]
