# Generated by Django 5.2.2 on 2025-06-12 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='type_transaction',
            new_name='methode_payement',
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('succes', 'Succès'), ('echec', 'Échec')], default='en attente', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='telephone',
            field=models.CharField(default=93150011, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portefeuille', to=settings.AUTH_USER_MODEL),
        ),
    ]
