# Generated by Django 5.2.2 on 2025-06-13 12:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0003_rename_type_transaction_transaction_methode_payement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portefeuille',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paygate_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('depot', 'Dépôt'), ('paiement', 'Paiement')], default='depot', max_length=35),
        ),
        migrations.AlterField(
            model_name='portefeuille',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='methode_payement',
            field=models.CharField(choices=[('mixx by yass', 'MIXX BY YASS'), ('flooz', 'FLOOZ')], default='mixx by yass', max_length=35),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('succes', 'Succès'), ('echec', 'Échec'), ('annule', 'Annulé')], default='en attente', max_length=20),
        ),
    ]
