# Generated by Django 5.2.2 on 2025-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0004_portefeuille_date_mise_a_jour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='methode_payement',
            field=models.CharField(choices=[('flooz', 'FLOOZ'), ('tmoney', 'TMONEY')], default='mixx by yass', max_length=35),
        ),
    ]
