# Generated by Django 5.2.2 on 2025-06-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0005_alter_transaction_methode_payement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='paygate_transaction_id',
            new_name='identifier',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference_paiement',
        ),
    ]
