# Generated by Django 5.2.2 on 2025-06-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0006_rename_paygate_transaction_id_transaction_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='methode_payement',
            field=models.CharField(choices=[('flooz', 'FLOOZ'), ('tmoney', 'TMONEY')], default='TMONEY', max_length=35),
        ),
    ]
