# Generated by Django 5.2.2 on 2025-06-13 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0008_transaction_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user_id',
        ),
    ]
