# Generated by Django 5.2.2 on 2025-06-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0009_remove_transaction_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
