# Generated by Django 5.2.2 on 2025-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0010_transaction_reference_externe'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='methode_payement',
            field=models.CharField(choices=[('FLOOZ', 'FLOOZ'), ('TMONEY', 'TMONEY')], default='TMONEY', max_length=35),
        ),
    ]
