# Generated by Django 5.2.2 on 2025-09-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0012_alter_transaction_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='statut',
            field=models.IntegerField(choices=[(0, 'Succès'), (2, 'En attente'), (4, 'Expiré'), (6, 'Annulé'), (-1, 'Echoué')], default=2),
        ),
    ]
