# Generated by Django 5.2.2 on 2025-09-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0013_alter_transaction_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='portefeuille_credite',
            field=models.BooleanField(default=False),
        ),
    ]
