# Generated by Django 5.2.2 on 2025-07-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
