# Generated by Django 5.2.2 on 2025-07-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0003_alter_prestation_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
