# Generated by Django 5.2.2 on 2025-07-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0004_prestation_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Acceptée'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
