# Generated by Django 5.2.2 on 2025-07-19 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0006_alter_prestation_prestataire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCiblee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to=settings.AUTH_USER_MODEL)),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_ciblees', to='prestations.prestation')),
            ],
            options={
                'unique_together': {('prestation', 'prestataire')},
            },
        ),
    ]
