# Generated by Django 5.2.2 on 2025-07-19 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0007_demandeciblee'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeciblee',
            name='est_acceptee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandeciblee',
            name='est_refusee',
            field=models.BooleanField(default=False),
        ),
    ]
