# Generated by Django 5.2.2 on 2025-07-20 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0008_demandeciblee_est_acceptee_demandeciblee_est_refusee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeciblee',
            old_name='date_envoi',
            new_name='date_demande',
        ),
        migrations.RemoveField(
            model_name='demandeciblee',
            name='est_acceptee',
        ),
        migrations.RemoveField(
            model_name='demandeciblee',
            name='est_refusee',
        ),
        migrations.AddField(
            model_name='demandeciblee',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeciblee',
            name='message_prestataire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeciblee',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Acceptée'), ('terminee', 'Terminée'), ('annulee', 'Annulée'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
