# Generated by Django 5.2.2 on 2025-07-20 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0009_rename_date_envoi_demandeciblee_date_demande_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandeciblee',
            old_name='date_demande',
            new_name='date_envoi',
        ),
        migrations.RemoveField(
            model_name='demandeciblee',
            name='date_reponse',
        ),
        migrations.RemoveField(
            model_name='demandeciblee',
            name='message_prestataire',
        ),
        migrations.RemoveField(
            model_name='demandeciblee',
            name='statut',
        ),
        migrations.AlterField(
            model_name='prestation',
            name='prestataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestaion_prestataire', to=settings.AUTH_USER_MODEL),
        ),
    ]
