# Generated by Django 5.2.2 on 2025-08-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0012_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='prestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='prestations.prestation'),
        ),
    ]
