# Generated by Django 5.2.2 on 2025-08-22 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0013_notification_prestation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestation',
            name='prestataire_cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestations_ciblees', to=settings.AUTH_USER_MODEL),
        ),
    ]
