# Generated by Django 5.2.2 on 2025-08-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0014_prestation_prestataire_cible'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorieprestation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categorie_images/'),
        ),
    ]
