# Generated by Django 5.2.2 on 2025-06-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField()),
            ],
        ),
    ]
