# Generated by Django 5.2.2 on 2025-06-10 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_initial'),
        ('note', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commandes.commande'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('client', 'commande')},
        ),
    ]
