# Generated by Django 5.2.2 on 2025-06-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note_commande_alter_note_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
    ]
