# Generated by Django 5.2.2 on 2025-06-17 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_alter_note_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='prestataire',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_notes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
