# Generated by Django 5.2.2 on 2025-08-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='est_prestataire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
    ]
