# Generated by Django 5.2.2 on 2025-09-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_resetpasswordtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResetPasswordToken',
        ),
    ]
