# Generated by Django 5.2.2 on 2025-09-29 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0015_categorieprestation_image'),
        ('service', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='prestation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestation', to='prestations.prestation'),
        ),
    ]
