# Generated by Django 5.2.2 on 2025-09-29 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestations', '0015_categorieprestation_image'),
        ('service', '0003_service_prestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='prestation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestation', to='prestations.prestation'),
        ),
    ]
